parameters:
#    clamz_cds_site.example.class: Clamz\CheminDuSon\SiteBundle\Example

services:
#    clamz_cds_site.example:
#        class: %clamz_cds_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    clamz_cds_site.menu_builder:
        class: Clamz\CheminDuSon\SiteBundle\Services\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]

    clamz_cds_site.menu.main:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: clamz_cds_site.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu