parameters:
#    clamz_chemin_du_son_user.example.class: Clamz\CheminDuSon\UserBundle\Example

services:
#    clamz_chemin_du_son_user.example:
#        class: %clamz_chemin_du_son_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
