<?php

namespace Clamz\CheminDuSon\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CoordonneesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoordonneesRepository extends EntityRepository
{
	public function createCoordonnee(Coordonnees $formData){
		$coordonnee = new Coordonnees();
		
		$coordonnee->setAdresse1($formData->getAdresse1());
		$coordonnee->setAdresse2($formData->getAdresse2());
		$coordonnee->setDepartement($formData->getDepartement());
		$coordonnee->setIsPrivate($formData->getIsPrivate());
		$coordonnee->setPays($formData->getPays());
		$coordonnee->setRegion($formData->getRegion());
		$coordonnee->setTelephone($formData->getTelephone());
		$coordonnee->setVille($formData->getVille());
		$coordonnee->setZipcode($formData->getZipcode());
		
		$em = $this->getEntityManager();
		$em->persist($coordonnee);
		$em->flush();
		return $coordonnee;
	}
}
