<?php

namespace Clamz\CheminDuSon\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	public function findByUsername2($name){
		return $this->findByUsername($name);
	}
	
	public function updateCoordonnee($userId,$coordonnee){
		$em = $this->getEntityManager();
		$user = $em->getRepository('ClamzCheminDuSonUserBundle:User')->find($userId);
		if (!$user) {
			throw $this->createNotFoundException('No user found for id '.$userId);
		}
		
		$user->setCoordonneesPrincipales($coordonnee);
		$em->flush();
	}
}
