<?php

namespace Clamz\CheminDuSon\BandBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BandMembersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BandMembersRepository extends EntityRepository
{
}
