<?php

namespace Clamz\CheminDuSon\BandBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BandRepository extends EntityRepository
{
}
