<?php

namespace Clamz\CheminDuSon\BandBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BandRepository extends EntityRepository
{
	function createBand($band, $tags){
		var_dump($band);
		$em = $this->getEntityManager();
		foreach ($tags as $tag){
			if($tag!==""){
				$tagEntity = $em->getRepository('CdsBandBundle:Tag')->findOneByName($tag);
				if($tagEntity===null){
					$tagEntity = new Tag();
				}
				$tagEntity->setName($tag);
				$band->addTag($tagEntity);
			}
		
		}
		
		$em->persist($band);
		$em->flush();
	}
}
